ElectronicPerformVideoCall/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('staffappraisal.urls')), #localhost:8000
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staffappraisal/urls.py
from django.urls import path

from . import views


app_name = 'staff'
urlpatterns = [
    path('', views.LoginView, name='login'), #localhost:8000 
    path('register', views.RegisterView.as_view(), name='register'), #localhost:8000/register
    path('users', views.ViewUsers.as_view(), name='users'), #localhost:8000/register
    path('list', views.ListCompetenceView.as_view(), name='list'), #localhost:8000/list
    path('comp', views.CompentenceCreateView, name='comp'),
    path('comm/<pk>', views.CommentView.as_view(), name='comm'),
    path('update_compentence/<pk>', views.CompetenceUpdateView.as_view(), name='update_compentence'),
    path('update_com/<pk>', views.AppraiseeCommentUpdate.as_view(), name='update_com'),
    path('update_assessment/<pk>', views.AppraiserAndAppraiseeAgreementView, name='update_assessment'),
    path('update_assess/<pk>', views.UpdateAppraiserAndAppraiseeAgreement, name='update_assess'),
    path('success', views.SuccessView.as_view(), name='success'),
    path('coma/<pk>', views.CommentappView.as_view(), name='coma'),
    path('comv/<pk>', views.CommentvcView.as_view(), name='comv'),
    path('prof', views.ProfileView.as_view(), name='prof'),
    path('act/<pk>', views.PerformanceView.as_view(), name='act'),
    path('as/<pk>', views.AssessmentView, name='as'),
    path('both', views.SuperandApprai.as_view(), name='both'),
    # path('profile', views.Profiles.as_view(), name='profile'),
    path('home' , views.IndexView.as_view(), name='index'),
    path('logout', views.LogoutView, name='logout'),
    path('add_user', views.Register, name='add_user'),
    path('detail/<pk>', views.AllDetailViewapp.as_view(), name='detail'),
    path('agreement/<pk>', views.AgreementView.as_view(), name='agreement'),
    path('edit/<pk>', views.EditOutput, name='editing'),
    path('editi/<pk>', views.UpdateOutputall.as_view(), name='editi'),
    path('listvc', views.ListCompetenceVCView.as_view(), name='listvc'),
    path('details/<pk>', views.AllDetailViewVC.as_view(), name='details'),
     #localhost:8000/list

    

]

staffappraisal/models.py
import decimal
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.dispatch import receiver
from django.db.models.signals import post_save

from django.core.validators import MinValueValidator,MaxValueValidator
# from django.
# Create your models here.
# done
class Faculty(models.Model):
    class Meta:
        verbose_name ="Faculty"
        verbose_name_plural ="Faculties"

    faculty_name = models.CharField(max_length=100)
    faculty_head= models.ForeignKey(User, help_text="Head of the faculty responsible for confirmations",  on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.faculty_name


class Department(models.Model):
    faculty = models.ForeignKey(Faculty, verbose_name='Select the Faculty to which the department Belongs', on_delete=models.CASCADE)
    department_name = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.department_name


class Profile(models.Model):
    role =  [
        ("u", "User"),
        ("s", "Supervisor"),
        ("h", "Human Resource"),
        ("v", "Vice Chancellor"),
    ]

    sex = [
        ("F", "Female"),
        ("M", "Male"),
    ]

    terms = [
        ("pro", "Probation"),
        ("per", "Permanant"),
        ("cont","Contract")
    ]
    salary =[
        ("m2","M2"),
        ("m3","M3"),
        ("m4","M4"),
        ("m5","M5"),
        ("m6","M6"),
        ("m7","M7"),
        ("m8","M8"),
    ]
    roles = models.CharField(max_length=2, choices=role, default='u')
    job_title = models.CharField(max_length=50, null=True, blank=True)
    salary_scale = models.CharField(max_length=2, choices=salary, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True)
    gender = models.CharField(max_length=2, choices=sex, blank=True, null=True)
    staff_dob = models.DateField(verbose_name='Staff date of birth', blank=True, null=True)
    f_appoi_date = models.DateField(verbose_name='Date of First Appointment', blank=True, null=True)
    s_appoi_date = models.DateField(verbose_name='Date of Latest Appointment', blank=True, null=True)
    terms_of_appoint = models.CharField(max_length=4, choices=terms, blank=True, null=True )
    photo = models.ImageField(upload_to ='staff_uploads', blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE,editable=False)

    def __str__(self) -> str:
        return self.user.get_full_name()


# class Competence(models.Model):
#     comps = [
#         ("profession_skill", "Professional Knowledge/ Skills"),
#         ("planning", "Planning, organizing and coordinating"),
#         ("leadership","Leadership"),
#         ("decision_making", "Decision making"),
#         ("innovation","Initiative & Innovation"),
#         ("team_work","Team work"),
#         ("human_resource","Human Resource Management:/Mentorship"),
#         ("fin_management","Financial management"),
#         ("o_resource_man","Management of other resources (equipment & facilities)"),
#         ("result_orientation","Result Orientation"),
#         ("client_care","Client Care"),
#         ("communication","Communication skills"),
#         ("integrity","Integrity"),
#         ("time","Time Management"),
#         ("loyalty","Loyalty")
#     ]
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     compentence_type = models.CharField(max_length=200, editable=True, choices=comps)
#     ranking = models.PositiveIntegerField(
#         validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))]
#     )
#     current_date = models.DateField(auto_now=True)
#     comment = models.CharField(max_length=255)

#     def __str__(self):
#         return self.user.username


class Competence(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profession_skill = models.PositiveIntegerField(verbose_name="Professional Knowledge/ Skills",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
        )
    comment_professional_skill =models.TextField(max_length=400,  blank=True, null=True)
    planning = models.PositiveIntegerField(verbose_name="Planning, organizing and coordinating",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_planning = models.TextField(max_length=400, blank=True,null=True)
    leadership = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_leadership=models.TextField(max_length=400,blank=True,null=True)
    decision_making = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_decision_making=models.TextField(max_length=400,blank=True,null=True)
    innovation = models.PositiveIntegerField(verbose_name="Initiative &Innovation",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_innovation=models.TextField(max_length=400,blank=True,null=True)
    team_work = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_teamwork=models.TextField(max_length=400,blank=True,null=True)
    human_resource = models.PositiveIntegerField(verbose_name="Human Resource Management:/Mentorship",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],blank=True,null=True
    )
    comment_human_resource=models.TextField(max_length=400,blank=True,null=True)
    fin_management = models.PositiveIntegerField(verbose_name="Financial management",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_financial_management=models.TextField(max_length=400,blank=True,null=True)

    o_resource_man = models.PositiveIntegerField(verbose_name="Management of other resources (equipment & facilities)",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_other_resource_mananagement=models.TextField(max_length=400,blank=True,null=True)
    result_orientation = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_result_orientation=models.TextField(max_length=400,blank=True,null=True)
    client_care = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_client_care=models.TextField(max_length=400,blank=True,null=True)
    communication = models.PositiveIntegerField(verbose_name="Communication skills",
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_communication=models.TextField(max_length=400,blank=True,null=True)
    integrity = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_integrity=models.TextField(max_length=400,blank=True,null=True)
    time_management = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_time_management=models.TextField(max_length=400,blank=True,null=True)
    loyalty = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True
    )
    comment_loyalty=models.TextField(max_length=400,blank=True,null=True)
    other_competence = models.PositiveIntegerField(
        validators=[MinValueValidator(decimal.Decimal(1)), MaxValueValidator(decimal.Decimal(5))],
        blank=True,null=True,verbose_name="Other Competences (specify in the Comment)"
    )
    comment_other_competence = models.TextField(max_length=500,blank=True, null=True)
    submitted_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user.get_full_name()

    @property
    def overallp(self):
        ps= int(self.profession_skill) if self.profession_skill else 0
        pl =int(self.planning) if self.planning else 0
        le =int(self.leadership) if self.leadership else 0
        dm =int(self.decision_making) if self.decision_making else 0
        inn =int(self.innovation) if self.innovation else 0
        tw =int(self.team_work) if self.team_work else 0
        hr =int(self.human_resource) if self.human_resource else 0
        fm =int(self.fin_management) if self.fin_management else 0
        orm =int(self.o_resource_man) if self.o_resource_man else 0
        ro =int(self.result_orientation) if self.result_orientation else 0
        cc =int(self.client_care) if self.team_work else 0
        co =int(self.communication) if self.team_work else 0
        inte =int(self.integrity) if self.team_work else 0
        tm =int(self.time_management) if self.team_work else 0
        loy =int(self.loyalty) if self.team_work else 0
        coc =int(self.comment_other_competence) if self.team_work else 0
        totalall = ps+pl+le+dm+inn+tw+hr+fm+orm+ro+cc+co+inte+tm+loy+coc

        num1 = 1 if self.professional_skill else 0
        num2 = 1 if self.planning else 0
        num3 = 1 if self.leadership else 0

templates/supervisor/action.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION D: ACTION PLAN TO IMPROVE PERFORMANCE
{% endblock page_title %}

{% block content %}
<!-- Collapsable Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
        role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h4 class="m-0 font-weight-bold text-primary">Guide</h4>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
        <div class="card-body">
           The Action Plan shall be jointly agreed during the performance appraisal meeting, taking into account the
           Appraisee’s required job competencies, and the identified performance gaps.  Such action plan for improved
           performance may include: Training, coaching, mentoring, job rotation, counseling among others.
           <b>Where the plan(s) involve formal training of the Appraisee, such record should be forwarded to
           the Human Resource Directorate.

           <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
           or expand the Body (to get more clarification)
        </div>            
</div>

<div class="card-header py-3">
    <h4 class="m-0 font-weight-bold text-primary">Action Plan</h4>
</div>
<form class="form-horizontal" method="POST">
    {% csrf_token %}
    <div class="card-body">
        {% for a in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{a.label_tag}}</div>
            <div class="col-sm-10">
                {{ a|add_class:"form-control" }}
                <br> {{ a.help_text }}
            </div>
            {% if a.errors %}
            {% for error in a.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>
            {% endfor %}        
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-info">Add Performance Gap (If there is any)</button>
    </div>
    {% comment %} {{ form }} {% endcomment %}
</form>
<p class="alert alert-success">Please check below to see the performance already added(If there is any)</p>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Performance Gap</th>
            <th>Agreed Action</th>
            <th>Time Frame</th>
        </tr>
    </thead>
    <tbody>
    {% for performance in performances reversed %}
    
        <tr>
            <td>{{performance.performance_gap}}</td>
            <td>{{performance.agreed_action}}</td>
            <td>{{performance.time_frame}}</td>
        </tr>

    {% endfor %}
    
    </tbody>
</table>
<a class="btn btn-info float-right" href= "{% url 'staff:agreement' view.kwargs.pk %}">Go to Edit the Outputs</a>

{% endblock content %}

templates/supervisor/assessment.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION B:  ASSESSMENT OF THE LEVEL OF ACHIEVEMENT (LAST TO BE ATTEMPTED) {{ view.kwargs.pk }}
{% endblock page_title %}

{% block content %}
<!-- Collapsable Card Example -->
<div class="card shadow mb-4">

    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
        role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h4 class="m-0 font-weight-bold text-primary">Guide</h4>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
   
        <div class="card-body">
 
           This section should be filled by both the Appraiser and the Appraisee. At the beginning of each assessment
           period, the Appraiser and Appraisee will agree on the key outputs for the assessment period. The means by
           which performance shall be measured (Performance Indicators) and the minimum level of performance
           (Performance targets) for each output shall be agreed upon.  If in the course of the assessment period,
           other activities are assigned to the Appraisee, the outputs related to the activities should be agreed
           upon and included immediately or at least before the end of the assessment period.  It is recommended that
           the maximum of outputs for each assessment period should not exceed 10.
           <br>At the end of the assessment period, an appraisal meeting should be conducted by the Appraiser.The Appraisee
           completes part B (1); before the appraisal meeting, by indicating the key outputs, performance indicators
           and targets agreed upon in the performance plan at the beginning of the assessment period.  The Appraiser
           should complete part B (2), after the appraisal meeting.  The assessment should reflect the jointly agreed position.
           <br>The assessment of the Individual outputs shall be reflected as a performance level under section B (20);
           this will be supported by relevant comments on performance under the same section.  The performance levels shall
           be described as Excellent, Very good, Good, Fair and Poor.  In order to quantify the assessment, the performance 
           levels shall be awarded scores namely; 5 for excellent, 4 for Very Good, 3 for Good, 2 for Fair and 1 for Poor.
           Right after the table is a detailed description of the performance levels.
           <br>
           <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
           or expand the Body (to get more clarification)
        </div>            
</div>

<div class="card-header py-3">
    <h4 class="m-0 font-weight-bold text-primary">Appraiser and Appraisee Communicate and Agree</h4>
</div>
<form class="form-horizontal" action='{% url "staff:as" competence.pk %}' method="POST">
    {% csrf_token %}
    <div class="card-body"> 
        {% for a in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{a.label_tag}}</div>
            <div class="col-sm-10">
                {{ a|add_class:"form-control" }}
                <br> {{ a.help_text }}
            </div>
            {% if a.errors %}
            {% for error in a.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>
            {% endfor %}        
    </div>
    <div class="card-footer">
        <button {% if assess < 10 %}type="submit" class="btn btn-info" {% else %} class="btn btn-inactive" inactive {% endif %}>Add Outputs</button>

        <a  {% if assess > 5 %}class="btn btn-info float-right" href='{% url 'staff:comm' competence.pk %}' {% else %} class="btn btn-inactive float-right" inactive {% endif %}>Proceed</a>
    </div>
                {% comment %} <a  {% if assess > 5 %}class="btn btn-info float-right" href= 'staff:update_assessment'>Continue to Update the Outputs</a> {% endcomment %}

    {% comment %} {{ form }} {% endcomment %}
</form>
{% endblock content %}

templates/supervisor/detail.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    Details About the Appraisal
{% endblock page_title %}
{% block content %}
<div class="card-body">
<fieldset>
    <legend>PERSONAL INFORMATION</legend>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <tbody>
                <tr>
                    <td>Name of Appraisee:</td>
                    <td>{{details.user.get_full_name}}</td>
                    <td>Date of birth:</td>
                    <td>{{details.user.profile.staff_dob}}</td>
                    <td>Current Job Title:</td>
                    <td>{{details.user.profile.job_title}}</td>
                </tr>
                <tr>
                    <td>Salary Scale:</td>
                    <td>{{details.user.profile.get_salary_scale_display}}</td>
                    <td>Date of 1st Appointment:</td>
                    <td>{{details.user.profile.f_appoi_date}}</td>
                    <td>Date of Latest Appointment:</td>
                    <td>{{details.user.profile.s_appoi_date}}</td>
                </tr>
                <tr>
                    <td>Terms of Appointment:</td>
                    <td contenteditable>{{details.user.profile.get_terms_of_appoint_display}}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>  
                <tr>
                    <td>Name of the Appraiser:</td>
                    <td>{{user.get_full_name}}</td>
                    <td>Job Title:</td>
                    <td>{{user.profile.job_title}}</td>
                    <td>Salary Scale:</td>
                    <td>{{user.profile.get_salary_scale_display}}</td>
                </tr>  
                <tr>
                    <td>Faculty/Institute/Unit:</td>
                    <td>{{user.profile.department.faculty.faculty_name}}</td>
                    <td>Department:</td>
                    <td>{{details.user.profile.department.department_name}}</td>
                    <td></td>
                    <td></td>
                </tr>                          
            </tbody>
        </table>
    </div>
</fieldset>
<fieldset>
    <legend>COMPETENCE</legend>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Competence</th>
                    <th>Rating</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Professional Knowledge/ Skills</td>
                    <td>{{details.profession_skill}}</td>
                    <td>{{details.comment_professional_skill}}</td>
                </tr>
                <tr>
                    <td>Planning, organizing and coordinating</td>
                    <td>{{details.planning}}</td>
                    <td>{{details.comment_planning}}</td>
                </tr>
                <tr>
                    <td>Leadership</td>
                    <td>{{details.leadership}}</td>
                    <td>{{details.comment_leadership}}</td>
                </tr>
                <tr>
                    <td>Decision making</td>
                    <td>{{details.decision_making}}</td>
                    <td>{{details.comment_decision_making}}</td>
                </tr>
                <tr>
                    <td>Initiative & Innovation</td>
                    <td>{{details.innovation}}</td>
                    <td>{{details.comment_innovation}}</td>
                </tr>
                <tr>
                    <td>Team work</td>
                    <td>{{details.team_work}}</td>
                    <td>{{details.comment_team_work}}</td>
                </tr>
                <tr>
                    <td>Human Resource Management/ Mentorship</td>
                    <td>{{details.human_resource}}</td>
                    <td>{{details.comment_human_resource}}</td>
                </tr>
                <tr>
                    <td>Financial management</td>
                    <td>{{competence.fin_management}}</td>
                    <td>{{competence.comment_financial_management}}</td>
                </tr>
                <tr>
                    <td>Management of other resources (equipment & facilities)</td>
                    <td>{{details.o_resource_man}}</td>
                    <td>{{details.comment_other_resource_mananagement}}</td>
                </tr>
                <tr>
                    <td>Result Orientation</td>
                    <td>{{details.result_orientation}}</td>
                    <td>{{details.comment_result_orientation}}</td>
                </tr>
                <tr>
                    <td>Client care</td>
                    <td>{{details.client_care}}</td>
                    <td>{{details.comment_client_care}}</td>
                </tr>
                <tr>
                    <td>Communication skills</td>
                    <td>{{details.communication}}</td>
                    <td>{{details.comment_communication}}</td>
                </tr>
                <tr>
                    <td>Integrity</td>
                    <td>{{details.integrity}}</td>
                    <td>{{details.comment_integrity}}</td>
                </tr>
                <tr>
                    <td>Time Management</td>
                    <td>{{details.time_management}}</td>
                    <td>{{details.comment_time_management}}</td>
                </tr>
                <tr>
                    <td>Loyalty</td>
                    <td>{{details.loyalty}}</td>
                    <td>{{details.comment_loyalty}}</td>
                </tr>
                <tr>
                    <td>Other Competence</td>
                    <td>{{competence.other_competence}}</td>
                    <td>{{details.comment_other_competence}}</td>
                </tr>                                        
            </tbody>
        </table>
    </div>
</fieldset>
<fieldset>
    <legend>APPRAISEE COMMENT</legend>
    <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <tbody>
                <tr>
                    <td>Describe how effectively you have been utilized by the University.</td>
                    <td>{{details.appraiseecomment.effectiveness}}</td>
                </tr>
                <tr>
                    <td>How would you like management to assist you in improving your performance?</td>
                    <td>{{details.appraiseecomment.assistance}}</td>
                </tr>
                <tr>
                    <td>What are your aspirations as far as career development is concerned?</td>
                    <td>{{details.appraiseecomment.aspiration}}</td>
                </tr>
                <tr>
                    <td>Any other comment?</td>
                    <td>{{details.appraiseecomment.any_comment}}</td>
                </tr>
                <tr>
                    <td>Comment Date</td>
                    <td>{{details.appraiseecomment.comment_date}}</td>
                </tr>                
            </tbody>
        </table>
    </div>
</fieldset>

    <div class="card-footer">
        <a class="btn btn-info float-center" href= "{% url 'staff:act' view.kwargs.pk %}">Go to Action Plan to the Appraisee</a>
    </div>
    {% comment %} {{ form }} {% endcomment %}
</div>
{% comment %} <form method="post" action="">
{% csrf_token %}
    {{ form }}
</form> {% endcomment %}

{% endblock content %}

templates/supervisor/editlast.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    ASSESSMENT OF THE LEVEL OF ACHIEVEMENT
{% endblock page_title %}

{% block content %}
<form method="POST" action="{% url 'staff:editi' object.pk %}">
{% csrf_token %}
{% comment %} {{form.as_p}} {% endcomment %}

<div class="card-body">
    {% for f in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{ f.label_tag }}</div>
            <div class="col-sm-10">
                {{ f|add_class:"form-control" }}
                <br> {{ f.help_text }}
        </div>
    {% if f.errors %}
    {% for error in f.errors %}
    <span class="text-danger">{{error}}</span>
    {% endfor %}
    {% endif %}
</div>
{% endfor %}
<input class="btn btn-info" type="submit" value="Add Your Rating and Comment" />
</form>
{% endblock content %}

templates/supervisor/last.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    ASSESSMENT OF THE LEVEL OF ACHIEVEMENT
{% endblock page_title %}
{% block content %}

    <p class="alert alert-success">These are already added Key Outputs, performance Indicators and Targets</p>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Key Outputs</th>
            <th>Performance Indicator</th>
            <th>Performance targets</th>
            <th>Self Rating</th>
            <th>Supervisors Rating</th>
            <th>Comments on Performance</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    {% for agreement in agreements reversed %}
        <form action="" method="POST">
        {% csrf_token %}
            <tr>
                <td>{{agreement.key_outputs}}</td>
                <td>{{agreement.performance_indicator}}</td>
                <td>{{agreement.performance_target}}</td>
                <td>{{agreement.self_rating}}</td>
                <td contenteditable='true'>{{agreement.supervisor_rating}}</td>
                <td contenteditable='true'>{{agreement.comments_on_performance}}</td>
                <td><a class="btn btn-info float-center" href= "{% url 'staff:editi' agreement.pk %}">Update</a></td>
            </tr>
        </form>

    {% endfor %}
    
    </tbody>
</table>
<a class="btn btn-info" href= "{% url 'staff:coma' view.kwargs.pk %}">Go to Your final Comment on this Performance Appraisal</a>

{% endblock content %}