ElectronicPerformVideoCall/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('staffappraisal.urls')), #localhost:8000
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staffappraisal/urls.py
from django.urls import path

from . import views


app_name = 'staff'
urlpatterns = [
    path('', views.LoginView, name='login'), #localhost:8000 
    path('register', views.RegisterView.as_view(), name='register'), #localhost:8000/register
    path('users', views.ViewUsers.as_view(), name='users'), #localhost:8000/register
    path('list', views.ListCompetenceView.as_view(), name='list'), #localhost:8000/list
    path('comp', views.CompentenceCreateView, name='comp'),
    path('comm/<pk>', views.CommentView.as_view(), name='comm'),
    path('update_compentence/<pk>', views.CompetenceUpdateView.as_view(), name='update_compentence'),
    path('update_com/<pk>', views.AppraiseeCommentUpdate.as_view(), name='update_com'),
    path('update_assessment/<pk>', views.AppraiserAndAppraiseeAgreementView, name='update_assessment'),
    path('update_assess/<pk>', views.UpdateAppraiserAndAppraiseeAgreement, name='update_assess'),
    path('success', views.SuccessView.as_view(), name='success'),
    path('coma/<pk>', views.CommentappView.as_view(), name='coma'),
    path('comv/<pk>', views.CommentvcView.as_view(), name='comv'),
    path('prof', views.ProfileView.as_view(), name='prof'),
    path('act/<pk>', views.PerformanceView.as_view(), name='act'),
    path('as/<pk>', views.AssessmentView, name='as'),
    path('both', views.SuperandApprai.as_view(), name='both'),
    # path('profile', views.Profiles.as_view(), name='profile'),
    path('home' , views.IndexView.as_view(), name='index'),
    path('logout', views.LogoutView, name='logout'),
    path('add_user', views.Register, name='add_user'),
    path('detail/<pk>', views.AllDetailViewapp.as_view(), name='detail'),
    path('agreement/<pk>', views.AgreementView.as_view(), name='agreement'),
    path('edit/<pk>', views.EditOutput, name='editing'),
    path('editi/<pk>', views.UpdateOutputall.as_view(), name='editi'),
    path('listvc', views.ListCompetenceVCView.as_view(), name='listvc'),
    path('details/<pk>', views.AllDetailViewVC.as_view(), name='details'),
     #localhost:8000/list

    

]

templates/users/action.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION D: ACTION PLAN TO IMPROVE PERFORMANCE
{% endblock page_title %}

{% block content %}
<!-- Collapsable Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
        role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h4 class="m-0 font-weight-bold text-primary">Guide</h4>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
        <div class="card-body">
           The Action Plan shall be jointly agreed during the performance appraisal meeting, taking into account the
           Appraisee’s required job competencies, and the identified performance gaps.  Such action plan for improved
           performance may include: Training, coaching, mentoring, job rotation, counseling among others.
           <b>Where the plan(s) involve formal training of the Appraisee, such record should be forwarded to
           the Human Resource Directorate.

           <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
           or expand the Body (to get more clarification)
        </div>            
</div>

<div class="card-header py-3">
    <h4 class="m-0 font-weight-bold text-primary">Action Plan</h4>
</div>
<form class="form-horizontal" method="POST">
    {% csrf_token %}
    <div class="card-body">
        {% for a in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{a.label_tag}}</div>
            <div class="col-sm-10">
                {{ a|add_class:"form-control" }}
                <br> {{ a.help_text }}
            </div>
            {% if a.errors %}
            {% for error in a.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>
            {% endfor %}        
    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-info">Add Performance Gap</button>
        
    </div>
    {% comment %} {{ form }} {% endcomment %}
</form>
<button type="submit" class="btn btn-info">Next Page or Section</button>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Performance Gap</th>
                    <th>Agreed Action</th>
                    <th>Time Frame</th>
                </tr>
            </thead>
            <tbody>
            {% for performance in performances reversed %}
            
                <tr>
                    <td>{{performance.performance_gap}}</td>
                    <td>{{performance.agreed_action}}</td>
                    <td>{{performance.time_frame}}</td>
                </tr>

            {% endfor %}
            
            </tbody>
</table>
{% endblock content %}

templates/users/assessment_update_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION B:  ASSESSMENT OF THE LEVEL OF ACHIEVEMENT 
{% endblock page_title %}

{% block content %}
<!-- Collapsable Card Example -->
{% comment %} <div class="card shadow mb-4"> {% endcomment %}

<div class="card-header py-3">
    <h4 class="m-0 font-weight-bold text-primary">Edit the key outputs </h4>
</div>

{% for object in objects reversed%}
<form class="form-horizontal" action="{% url 'staff:update_assess' object.pk %}" method="POST">
    {% csrf_token %}
    <div class="card-body"> 
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{form.key_outputs.label_tag}}</div>
            <div class="col-sm-10">
                {% comment %} {{ a|add_class:"form-control" }} {% endcomment %}
                {% render_field form.key_outputs value=object.key_outputs class='form-control' %}
                <br>
            </div>
            {% if form.key_outputs.errors %}
            {% for error in form.key_outputs.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>

        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{form.performance_indicator.label_tag}}</div>
            <div class="col-sm-10">
                {% comment %} {{ a|add_class:"form-control" }} {% endcomment %}
                {% render_field form.performance_indicator value=object.performance_indicator class='form-control' %}
                <br>
            </div>
            {% if form.performance_indicator.errors %}
            {% for error in form.performance_indicator.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>

        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{form.performance_target.label_tag}}</div>
            <div class="col-sm-10">
                {% comment %} {{ a|add_class:"form-control" }} {% endcomment %}
                {% render_field form.performance_target value=object.performance_target class='form-control' %}
                <br>
            </div>
            {% if form.performance_target.errors %}
            {% for error in form.performance_target.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>

        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{form.self_rating.label_tag}}</div>
            <div class="col-sm-10">
                {% comment %} {{ a|add_class:"form-control" }} {% endcomment %}
                {% render_field form.self_rating value=object.self_rating class='form-control' %}
                <br>
            </div>
            {% if form.self_rating.errors %}
            {% for error in form.self_rating.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>


    </div>
    <div class="card-footer">
        <button type="submit" class="btn btn-info">Update {{object.key_outputs}}</button>

    </div>
    {% comment %} {{ form }} {% endcomment %}
</form>
{% endfor %}

{% endblock content %}

templates/users/comment_update_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION E: COMMENTS, RECOMMENDATIONS (IF ANY) AND SIGNATURES
{% endblock page_title %}

{% block content %}

<!-- Collapsable Card Example -->

<div class="card-header py-3">
          <h4 class="m-0 font-weight-bold text-primary">Update Your Comments Before the Supervisor Signs</h4>
</div>
<form class="form-horizontal" method="POST">
    {% csrf_token %}
    <div class="card-body">
        {% for a in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{a.label_tag}}</div>
            <div class="col-sm-10">
                {{ a|add_class:"form-control" }}
                <br> {{ a.help_text }}
            </div>
            {% if a.errors %}
            {% for error in a.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>
            {% endfor %}        
    </div>
    <div class="card-footer">
    <button type="submit" class="btn btn-info">Update Your Comments from here and Terminate</button>
    </div>
    {% comment %} {{ form }} {% endcomment %}
</form>
{% endblock content %}

templates/users/comments.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION E: COMMENTS, RECOMMENDATIONS (IF ANY) AND SIGNATURES
{% endblock page_title %}

{% block content %}

<!-- Collapsable Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Accordion -->
    <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
        role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h4 class="m-0 font-weight-bold text-primary">Guidance on this Section</h4>
    </a>
    <!-- Card Content - Collapse -->
    <div class="collapse show" id="collapseCardExample">
        <div class="card-body">
            This section is to be completed by the Appraisee, Appraiser and the counter signing Officers.
            It is to confirm that the appraisal meeting actually took place and that there was agreement or 
            if there was a disagreement, it was resolved.  It further confirms that the action plan to improve
            performance was discussed and agreed upon.  So, the above concerned parties should use this 
            section to comment about the job, career and any other relevant information.
            <br>
            
            <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
            or expand the Body (to get more clarification)
        </div>            
</div>
<div class="card-header py-3">
          <h4 class="m-0 font-weight-bold text-primary">Fill this Form</h4>
</div>
<form class="form-horizontal" method="POST">
    {% csrf_token %}
    <div class="card-body">
        {% for a in form.visible_fields %}
        <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{a.label_tag}}</div>
            <div class="col-sm-10">
                {{ a|add_class:"form-control" }}
                <br> {{ a.help_text }}
            </div>
            {% if a.errors %}
            {% for error in a.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
        </div>
            {% endfor %}        
    </div>
    <div class="card-footer">
    <button type="submit" class="btn btn-info">Submit Your Comments and proceed</button>
    </div>
    {% comment %} {{ form }} {% endcomment %}
</form>
{% endblock content %}

templates/users/commentsapsee.html
{% extends "base.html" %}

{% block page_title %}
    SECTION E: COMMENTS, RECOMMENDATIONS (IF ANY) AND SIGNATURES
{% endblock page_title %}

{% block content %}

<!-- Collapsable Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
            role="button" aria-expanded="true" aria-controls="collapseCardExample">
            <h4 class="m-0 font-weight-bold text-primary">Guidance on this Section</h4>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                This section is to be completed by the Appraisee, Appraiser and the counter signing Officers.
                It is to confirm that the appraisal meeting actually took place and that there was agreement or 
                if there was a disagreement, it was resolved.  It further confirms that the action plan to improve
                performance was discussed and agreed upon.  So, the above concerned parties should use this 
                section to comment about the job, career and any other relevant information.
                <br>
                
                <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
                or expand the Body (to get more clarification)
            </div>            
    </div>
    <div class="card shadow mb-4o">
        <div class="card-header py-3">
          <h4 class="m-0 font-weight-bold text-primary">Fill this Form</h4>
        </div>
        
        <form class="form-horizontal">
          <div class="card-body">
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Describe how effectively you have been utilized by the University.
              </label>
              <div class="col-sm-10">
                <textarea class="form-control" id="ranking" placeholder="comment here ..."></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">How would you like management to assist you in improving your performance?
              </label>
              <div class="col-sm-10">
                <textarea class="form-control" id="ranking" placeholder="comment here ..."></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">What are your aspirations as far as career development is concerned?
              </label>
              <div class="col-sm-10">
                <textarea class="form-control" id="ranking" placeholder="comment here ..."></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Any other comment?
              </label>
              <div class="col-sm-10">
                <textarea class="form-control" id="ranking" placeholder="comment here ..."></textarea>
              </div>
            </div>
          </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-info">Save</button>
          </div>
          <!-- /.card-footer -->
        </form>

        
    </div>
{% endblock content %}

templates/users/competence.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION C: ASSESSMENT OF CORE COMPETENCIES
{% endblock page_title %}

{% block content %}

<!-- Collapsable Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
            role="button" aria-expanded="true" aria-controls="collapseCardExample">
            <h4 class="m-0 font-weight-bold text-primary">Guidance on this Section</h4>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse show" id="collapseCardExample">
            <div class="card-body">
                This section should be filled by the Appraiser after joint discussions between him/her and the 
                Appraisee. The assessment will help establish any areas where some training or development is 
                necessary. The Appraisee should be rated only in areas, which are relevant to his/her job.
                The maximum points per competence are <strong>5, which represents Excellent, 4-very Good, 3-Good, 2-Fair,
                1-Poor, Choose Only Applicable.</strong>
                <br>
                The Appraiser should give work related examples under comments, to justify their rating.
                functionality.
                <br>
                <br>
                <strong>Click on the header</strong> to collapse (after understanding how to fill the table below)
                or expand the Body (to get more clarification)
            </div>            
    </div>
    <div class="card shadow mb-4o">
        <div class="card-header py-3">
          <h4 class="m-0 font-weight-bold text-primary">Fill this first form</h4>
        </div>
        
        <form class="form-horizontal" action='{% url 'staff:comp' %}' method="POST">
         {% csrf_token %} 
          <div class="card-body">
          {% for f in form.visible_fields %}
            <div class="form-group row">
            <div class="col-sm-2 col-form-label">{{ f.label_tag }}</div>
            <div class="col-sm-10">
          {{ f|add_class:"form-control" }}
           <br> {{ f.help_text }}
           </div>
          {% if f.errors %}
          {% for error in f.errors %}
           <span class="text-danger">{{error}}</span>
          {% endfor %}
          {% endif %}
            </div>
          {% endfor %}


          </div>
          <!-- /.card-body -->
          <div class="card-footer">
            <button type="submit" class="btn btn-info">Submit Your Comments and proceed</button>
            {% comment %} <button type="submit" class="btn btn-info">Save</button> {% endcomment %}
          </div>
          <!-- /.card-footer -->
        </form>
    </div>


{% endblock content %}

templates/users/competence_update_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page_title %}
    SECTION C: ASSESSMENT OF CORE COMPETENCIES
{% endblock page_title %}

{% block content %}

    <div class="card shadow mb-4o">
        <div class="card-header py-3">
          <h4 class="m-0 font-weight-bold text-primary">Update Your Competence before the Supervisor Signs It </h4>
        </div>
        
        <form class="form-horizontal" method="POST">
            {% csrf_token %} 
            <div class="card-body">
                {% for f in form.visible_fields %}
                    <div class="form-group row">
                    <div class="col-sm-2 col-form-label">{{ f.label_tag }}
            </div>
            <div class="col-sm-10">
                {{ f|add_class:"form-control" }}
                <br> {{ f.help_text }}
            </div>
            {% if f.errors %}
            {% for error in f.errors %}
            <span class="text-danger">{{error}}</span>
            {% endfor %}
            {% endif %}
            </div>
            {% endfor %}

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-info" >Update your competence</button>
                <a class="btn btn-info float-center" href= "{% url 'staff:update_assessment' view.kwargs.pk %}">Continue to Update the Outputs</a>
                <a class="btn btn-info float-right" href= "{% url 'staff:update_com' object.appraiseecomment.pk %}">Continue to Update Your Comments</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>

{% endblock content %}

templates/users/exists.html
{% extends "base.html" %}

{% block content %}
    <div class='card bg-info'>

    <h1 class='card-title'>Oops!! Sorry {{user.username}} we cannot do that.</h1>
    <div class='card-body'>
        <div class='alert alert-danger'>
            We only allow applying for a new proposal in a month time frame. You will have to wait for the next month to re-apply.
        </div>
    </div>
    </div>
{% endblock content %}

templates/users/index.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}
{% comment %} user --> to every table that has a relationship to the User model ===user.competence {% endcomment %}
<div class="alert alert-danger">
    <b>
        Dear {{user.first_name}},</b> <br>Welcome To your Electronically Automated Performance
        Appraisal Account, You are now ready to Appraise as A {{user.profile.job_title}}.
    <br>
    <b>Preamble</b>
    <br>
        This performance management tool is for establishing the extent to which set targets within the overall goals 
        of the university are achieved.  Performance gaps are discovered and development needs of an individual 
        employee are identified as the appraisal process offers an opportunity to the Appraisee and Appraiser 
        to dialogue and obtain feedback on performance.  The process should therefore be participatory in 
        nature, and consistent in the use of guidelines by all Public Officers in filling the form.
    <br><br>
        The Appraiser and Appraisee are therefore, advised to read the detailed guidelines before filling this form.

    <br>
        This is always done at a specific period of Time, always take time to inquire about when it is done.
</div>
<div class="alert alert-danger">
    <b>It is advisable to always fill this form. it is more important most especially during promotion of
    workers. Please make sure that you have not missed any chance of filling this form. Please read the
     information above and understand it well before you fill the form. Thanks for being responsible.</b>
</div>


{% endblock content %}

templates/users/success.html
{% extends "base.html" %}

{% block page_title %}
<div class='text-center text-success font-weight-bold h1 '>
    *********************************************************
</div>
{% endblock page_title %}

{% block content %}

    <div class='text-center text-success font-weight-bold h1 '>Congraturations!!!</div>
    <div class='text-center text-success font-weight-bold'>
        Dear {{user.first_name}}, 
        Your appraisal has been successfully placed! <br>
    
        The only available option to appraise now is to edit the submitted Appraisal Until before
        the supervisor can review and sign it.<br>
        Else wait for another Appraising period.
        Otherwise thank you for Your time to Fill this Form<br>
        The management wishes You well for Your requirement!
    </div>


{% endblock content %}

templates/users/users.html
{% extends "base.html" %}

{% block page_title %}
    Users
{% endblock page_title %}

{% block content %}

<div class="alert alert-danger">Welcome to users, {{user.first_name}} {{user.last_name}}</div>


{% endblock content %}